---
- name: this playbook verifies and fixes settings on RHEL machines
  hosts: all
  become: yes

- name: Start the firewalld service
  service:
    name: firewalld
    state: started
    enabled: true

- name: Make sure selinux is running
  selinux:
    policy: targeted
    state: enforcing
